namespace CodeChallenges
{
    using System;
    using Strings;

    internal class Program
    {
        public static void Main(string[] args)
        {
            MinStringWindow s = new MinStringWindow();

            string result = s.MinWindow("obzcopzocynyrsgsarijyxnkpnukkrvzuwdjldxndmnvevpgmxrmvfwkutwekrffnloyqnntbdohyfqndhzyoykiripdzwiojyoznbtogjyfpouuxvumtewmmnqnkadvzrvouqfbbdiqremqzgevkbhyoznacqwbhtrcjwfkzpdstpjswnpiqxjhywjanhdwavajrhwtwzlrqwmombxcaijzevbtcfsdcuovckoalcseaesmhrrizcjgxkbartdtotpsefsrjmvksqyahpijsrppdqpvmuocofuunonybjivbjviyftsyiicbzxnwnrmvlgkzticetyfcvqcbjvbufdxgcmesdqnowzpshuwcseenwjqhgsdlxatamysrohfnixfprdsljyyfhrnnjsagtuihuczilgvtfcjwgdhpbixlzmakebszxbhrdibpoxiwztshwczamwnninzmqrmpsviydkptjzpktksrortapgpxwojofxeasoyvyprjoguhqobehugwdvtzlenrcttuitsiijswpogicjolfxhiscjggzzissfcnxnvgftxvbfzkukqrtalvktdjsodmtgzqtuyaqvvrbuexgwqzwduixzrpnvegddyyywaquxjxrnuzlmyipuqotkghfkpknqinoidifnfyczzonxydtqroazxhjnrxfbmtlqcsfhshjrxwqvblovaouxwempdrrplefnxmwrwfjtebrfnfanvvmtbzjesctdgbsfnpxlwihalyiafincfcwgdfkvhebphtxukwgjgplrntsuchyjjuqozakiglangxkttsczhnswjksnuqwflmumpexxrznzwxurrysaokwxxqkrggytvsgkyfjrewrcvntomnoazmzycjrjrqemimyhriyxgrzcfuqtjhvjtuhwfzhwpljzajitrhryaqchnuawbxhxrpvyqcvhpggrpplhychyulijhkglinibedauhvdydkqszdbzfkzbvhldstocgydnbfjkcnkfxcyyfbzmmyojgzmasccaahpdnzproaxnexnkamwmkmwslksfpwirexxtymkmojztgmfhydvlqtddewjvsrmyqjrpycbmndhupmdqqabiuelacuvxnhxgtpvrtwfgzpcrbhhtikbcqpctlxszgpfbgcsbaaiapmtsucocmpecgixshrrnhyrpalralbccnxvjzjllarqhznzghswqsnfuyywmzbopyjyauknxddgdthlabjqtwxpxwljvoxkpjjpfvccyikbbrpdsyvlxscuoofkecwtnfkvcnzbxkeabtdusyhrqklhaqreupakxkfzxgawqfwsaboszvlshwzhosojjotgyagygguzntrouhiweuomqptfjjqsxlbylhwtpssdlltgubczxslqjgxuqnmpynnlwjgmebrpokxjnbiltvbebyytnnjlcwyzignmhedwqbfdepqakrelrdfesqrumptwwgifmmbepiktxavhuavlfaqxqhreznbvvlakzeoomykkzftthoemqwliednfsqcnbexbimrvkdhllcesrlhhjsspvfupxwdybablotibypmjutclgjurbmhztboqatrdwsomnxnmocvixxvfiqwmednahdqhxjkvcyhpxxdmzzuyyqdjibvmfkmonfxmohhshpkhmntnoplphqyprveyfsmsxjfosmicdsjrieeytpnbhlsziwxnpmgoxneqbnufhfwrjbqcsdfarybzwaplmxckkgclvwqdbpumsmqkswmjwnkuqbicykoisqwoootrdpdvcuiuswfqmrkctsgrevcxnyncmivsxbpbxzxpwchiwtkroqisnmrbmefbmatmdknaklpgpyqlsccgunaibsloyqpnsibwuowebomrmcegejozypjzjunjmeygozcjqbnrpakdermjcckartbcppmbtkhkmmtcngteigjnxxyzaibtdcwutkvpwezisskfaeljmxyjwykwglqlnofhycwuivdbnpintuyhtyqpwaoelgpbuwiuyeqhbvkqlsfgmeoheexbhnhutxvnvfjwlzfmvpcghiowocdsjcvqrdmkcizxnivbianfpsnzabxqecinhgfyjrjlbikrrgsbgfgyxtzzwwpayapfgueroncpxogouyrdgzdfucfrywtywjeefkvtzxlwmrniselyeodysirqflpduvibfdvedgcrzpzrunpadvawfsmmddqzaaahfxlifobffbyzqqbtlcpquedzjvykvarayfldvmkapjcfzfbmhscdwhciecsbdledspgpdtsteuafzbrjuvmsfrajtulwirzagiqjdiehefmfifocadxfuxrpsemavncdxuoaetjkavqicgndjkkfhbvbhjdcygfwcwyhpirrfjziqonbyxhibelinpllxsjzoiifscwzlyjdmwhnuovvugfhvquuleuzmehggdfubpzolgbhwyeqekzccuypaspozwuhbzbdqdtejuniuuyagackubauvriwneeqfhtwkocuipcelcfrcjcymcuktegiikyosumeioatfcxrheklookaqekljtvtdwhxsteajevpjviqzudnjnqbucnfvkybggaybebljwcstmktgnipdyrxbgewqczzkaxmeazpzbjsntltjwlmuclxirwytvxgvxscztryubtjweehapvxrguzzsatozzjytnamfyiitreyxmanhzeqwgpoikcjlokebksgkaqetverjegqgkicsyqcktmwjwakivtsxjwrgakphqincqrxqhzbcnxljzwturmsaklhnvyungjrxaonjqomdnxpnvihmwzphkyuhwqwdboabepmwgyatyrgtboiypxfavbjtrgwswyvcqhzwibpisydtmltbkydhznbsvxktyfxopwkxzbftzknnwipghuoijrbgqnzovxckvojvsqqraffwowfvqvfcmiicwitrhxdeombgesxexedlakitfovtydxunqnwqqdeeekiwjnwoshqcsljiicgobbbuqakjdonjawgjlezdnqhfdqnmsuavxdpnfzwipmspiabveaarshzwxmirgkmfncvtdrdvfxkpxlkdokxgtwcskmjryyymcthfnkasinihaunohkxaibtsqelockaefjmsuolebtnepauwmrxutspjwaxbmahsjtkfkxlnszribmeofbkyvbjscjtqjakuwvcgunvnonvqbbggfshauqsyznokqbhowjusypfnecffenojfvlblgzntqzlrgzprvhqnpfrrkzxznieiuivajivzijsqijigtatifmbplzqahuidegfoobpymkputzamzvweiyvvzlwihgmmmrcburbgbsdxrfjsbiylitghgcpqjbevvgypxcybubyoijijrhuzcdijfybqbfowlookqmlnplbxvjjosfqviygqyhgamuwzjklbyzopkrnhbywtfoqomweldmlrhjqswctubiknzzvcztyehouvnyiqnvkufaobehxhrjvtisxjlxoumipzjarwvbsaegdkpbsjmpevjbewzuqnfhoohhmdjgfpmjzdmtmykqvtucptwfidpwtwffzolffzqfdearclkyeecuzabjeqhxpmfodsvisnpxrqowdawheydfyhoexvcmihdlzavtqlshdhdgjzpozvvackebhgqppvcrvymljfvooauxcjnbejdivikcoaugxwzsulgfqdtefpehbrlhaoqxwcancuvbqutnfbuygoemditeagmcveatgaikwflozgdhkyfqmjcruyyuemwbqwxyyfiwnvlmbovlmccaoguieu"
,"cjgamyzjwxrgwedhsexosmswogckohesskteksqgrjonnrwhywxqkqmywqjlxnfrayykqotkzhxmbwvzstrcjfchvluvbaobymlrcgbbqaprwlsqglsrqvynitklvzmvlamqipryqjpmwhdcsxtkutyfoiqljfhxftnnjgmbpdplnuphuksoestuckgopnlwiyltezuwdmhsgzzajtrpnkkswsglhrjprxlvwftbtdtacvclotdcepuahcootzfkwqhtydwrgqrilwvbpadvpzwybmowluikmsfkvbebrxletigjjlealczoqnnejvowptikumnokysfjyoskvsxztnqhcwsamopfzablnrxokdxktrwqjvqfjimneenqvdxufahsshiemfofwlyiionrybfchuucxtyctixlpfrbngiltgtbwivujcyrwutwnuajcxwtfowuuefpnzqljnitpgkobfkqzkzdkwwpksjgzqvoplbzzjuqqgetlojnblslhpatjlzkbuathcuilqzdwfyhwkwxvpicgkxrxweaqevziriwhjzdqanmkljfatjifgaccefukavvsfrbqshhswtchfjkausgaukeapanswimbznstubmswqadckewemzbwdbogogcysfxhzreafwxxwczigwpuvqtathgkpkijqiqrzwugtr");
            W(result);

            result = s.MinWindow("ADOBECODEBANC", "ABC");
            W(result);
            result = s.MinWindow("ueeouptjcosytyujjcvnmtndauseqxvkdzayrtjvhdtcbnnmrjbfeokfkdjacgnhfnhwjqtsumvvckkvtlbaclfmqqpuwecdtjccavxwiutmedhapkarwhfozwlxapauyeyaavwkpswwvdwmqydoflcejpbkedgdieficeutwqrtvnglllzswewgtzsadydlekvgqpcmhtgejmqwxrpwxletnwtquybakyjbnlnuevynjqmjkbfjojcbhxrdvudismjhxybeuctdsfoegtoxesylqsonouvhgeqgdsmzwfeontvvojstbtgrlxhzrcixjzfmtrnpzrfomalbjeunzcemzllqqwqzxxnqpahqtmggprhyxdlwfsiffwxvspwrnjheloufccnrtusrzfpexalfwjcqyzhnkqrygnfipsclmuclbtrztdgroihojqcwgvumjzxarblfxpsyjjxeofwcqftzwvvesrrbsqcjrpqofimqsmuitsljyejubgytarxsjbecqusxdhnxvifoasyayjwbrxvtoumaxsenmxlrgaqbiyrlqrlraksuhppxjdxgvcwibjbhjukusbfitsbveupljhjvkgdgkzqnirwulgofivqbprwulofvvoshxvnjvdzfxvzkcnqmkgnazlulbbiyqagpvvaszzyyvxkxncjxkyzklvvnxfnpfvearetsgtsbscafflfrlgbwcylzdboiwulnagfgzxhrcjzjugafmceocrpgsdqpzbcahkggjoalzzuuhxbtzfkdxzjpdagcdlenxltgbvuawqwdnyxofhsegdulfcqjnuwkhrtinnljdhptfmhlvbpdflpkqhtddrqljjtywejb"
                , "oyutmeghfylklcvbjqfmkxx");
            W(result);
            result = s.MinWindow("uezzciucmurfzinanwbwogiulgtwjdefhfekqbocxhjzswbhudeijmdwuwsdbzkieruuukytshsmgutaxxjgloefmzknyxxeosbkcbdwlwirqetpbcxpsbweajtagrfwjggnjjkuhunxyhmcllrennknweoexvagdgvm"
                , "shjz");
            W(result);
            result = s.MinWindow("tkopjjgknziznmfwvkgospwkujjklzugjiwvuefhepiteppbzyptplekwnwjmqqybovvsccyrnuxclyclnvbaznxojgdzydcmyxhacftpbrrnrvyftbfuoelxlozjtbyrbftdkoumhnbzlzgeblarslpdbqoutmnwrgzexvsejtfwulcxzcprqgwrykorxboqkpwhnonyjvuggwdfauyqauiafyseziwjztsojimvdiblegrhdrxdmhetfyxfitqjolaytmtyxwjdeckhuingptbxtyedtumihmgcbbayxkbdomliwyqnrrkmropllbvsqbvtexrdjugyirierzsksewktlxepsyhvvabttecpkayejevkyiedeqwsncjhascwudrnjteuwcahhxtffxkmoggdkpllhpjbvcqevuatzaaiyvpftarjixmtoxgxnraitsoqnpkormwpilxbnomwoypcwvclocvhvlxkajaswwjejghzxtvltmprjrcxwzetldfnnffjdrpoxynurkhmwxefqieoikhvooibvqmyhdpgbcdunkgljktatxqdiaywoizkynkhqzqretntftepgxrzvjcdjcbykcklpwufykycfnvngzcmzvnwerzotcogearvwncuaayfptsvvwkwtzsyrtokveqbgjwexyzxazepvzmqvymryeppxfbuluvrdtvcrwbtwikthwjevxvvdmmcrnyehvvnotrhrvcndmgkirofqkavwmzqcxwluuyinsrentuqfccqwqvocykbmltolpafjaqyshfhbbzidbybuwqwuczgnsxykxgvxwusdbbgcbrfcpjwnzvhbuqqpnrzmxujtqdyrfhvgydkpmjdlemoacgprzqdwnprfssxzz"
                , "ufzxqojzrufekhitzcsphr");
            W(result);
            result = s.MinWindow("tfsxfpbgrvlgngmrtgotjumbaxosseklkckrrlzljnrytfpolgjxcvycvounteafgkyaxylgleeglwuycfvecvgxmbmfhmmoykoykbgxhndsjzqneorjlzgxctckhqaibqgnrolybqskskxyyqhmqojsjocqeeyhugvlvglwwfjqqipqzwcrmmjvcoogsmopvjaqroontzglivcjtgagslbwbpdwetlbcnrtdhizhokploafvanpnqmpirnmkynmnghrnrqwicltrlaonndbersmihyshnguvplkhdhpgukxillvyqycksoszongdvbyloluusjamvzugmsfesjolahkqwturuuekhyezjgoffilrcswvekgetsurlqjhnpuuoywxfkcmuqexicumocsiupbihkrwclrqkpnrzsdvijuslohaqzknqlxyyouaansmehddzibjuvcfkjhcktrdhobhdxjfnbrriwxkgytatvifgpktlbwsqxzvwiajltdtradxazytugbdxlwimscerbbnldzwwcspexnewnzrvausnsdckfibhkquprrmvjdzgqfdffwahsvxkyzwdhzmtpjjhaxclaettjyyqwbaqwxauyyzfxobpxkyzjakjgfesediaekrchtwhuxnrlqikcgjljvwpbbhfgshmcaomwmtqjijxysjaatnjokzrlgwragddirrefkwqvintazwasjkitlaetyxueazptqtycsrxaetcfpcxaogwbicvgarncqcwixwmpnkpufrzwwzwmhsopvlxxckzumxcmwoblatffmhbiiaxpulgrydoaqquenyqjouvpncwzlaktahkwuqouweumuqqiohtcbotqtqpesbyukiqgbgaxlujfkzpagjfjzyzsqrxksxedfvjidkfogowtqltyuaiubjoraletiiyqfhyjtgzcuvvkhqjdrtzucoldbrymaweffcqbkqdflyruqcyjvzd"
                , "ynrdribdizhqelgfwwid");
            W(result);
            result = s.MinWindow(
                "rsfvquycmabtdxcmgwnoxiicpzxczxnspungqokcolwtlahrzvhwfqawraytxoloibuzpgdfsbbdeiwdddbivcenefidttrbuoclugtmjurncpqitssqwzdcelfxhwadkdrhlktueniicaqxulosktuohbnqantmsktdupaaeilgkdgfowzapuoyxdoxriklufprurtabehlipsylszampzltpjmxvxucolzfezglgutvmtgesjsikedzppzkotmdelkknrvvnqrzkzeekwmucpwrgvdvosaufkgsdeoquhqggwltuxpxplovguswmssrdzkidyzzfrgnnrghqwghjvfqpxodshuvgefjeeijvqzkjhsafyhpvohmmvpecmbkqgvxnggkwhvgppiwprlngubuqryufbfvjcsyibjhkgpbxxyoolbwgdqwwqsbtzydctdmwovgukkthiiytjwzonxkfsnzroevhhifydnsqxozhwzbhwcwlciquyrlmvhvfradwpxmnnoujnxtjcpueznyzellcuijnkokanypbmlmcjhllyiryxpxdclfxtqkeewguxvxlglnptbcrjtpikplnatmvjybqvhkucjfjutanufffawnnlacntoldmmtjufdwo",
                "jhkeiyapffpbu");
            W(result);
            result = s.MinWindow("abBaaabAb", "Bbb");
            W(result);

            result = s.MinWindow("ask_not_what_your_country_can_do_for_you_ask_what_you_can_do_for_your_country", "ask_country");
            W(result);
            result = s.MinWindow("a", "aa");
            W(result);
            result = s.MinWindow("acbbaca", "aba");
            W(result);
            result = s.MinWindow("cabwefgewcwaefgcf", "cae");
            W(result);
            

            Console.ReadLine();
        }

        private static void W(object o)
        {
            Console.WriteLine(o);
        }
    }
}